# Generated by Django 4.2.5 on 2024-12-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_organazations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organazations',
            name='icon',
        ),
        migrations.AddField(
            model_name='organazations',
            name='image',
            field=models.ImageField(default='image', upload_to='organazations'),
        ),
    ]
