# Generated by Django 4.2.5 on 2024-12-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='name',
            field=models.CharField(default='defaultname', max_length=100),
        ),
    ]
