# Generated by Django 4.2.5 on 2024-12-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_pictures_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=models.ImageField(upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
