# Generated by Django 4.2.5 on 2024-12-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_forms_alter_pictures_image_alter_pictures_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='image',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
